import Head from "next/head";
import Image from "next/image";
import React from "react";

interface LayoutProps {
  children: React.ReactNode;
}

const navItems = [
  { name: "HOME" },
  { name: "HOW IT WORKS" },
  { name: "SHOP" },
  { name: "CONTACT US" },
];

const DefaultLayout = ({ children }: LayoutProps) => {
  return (
    <div className="drawer bg-white">
      <Head>
        <title>Smart Derm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content ">
        {/* Navbar  */}
        <div className="w-full navbar py-0 px-0 bg-white border-t-4 border-blue-600">
          <div className="container mx-auto w-full flex justify-between px-0  ">
            <div className="flex  items-center ">
              <Image
                src="/assets/img/moreplex-logo.png"
                height={40}
                width={230}
                className="sm:h-[65px] h-[45px]"
                alt="spectrumfibre"
              />
            </div>
            <div className="flex-none hidden md:block ">
              <ul className="menu menu-horizontal text-black ">
                {navItems.map((navItem, i) => (
                  <li key={i}>
                    <a className="font-semibold rounded-md font-montserrat">
                      {navItem.name}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            {/* visible only on mobile */}
            <div className="flex-none md:hidden ">
              <label htmlFor="my-drawer-3" className="btn btn-square btn-ghost">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  className="inline-block w-6 h-6 stroke-current"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 6h16M4 12h16M4 18h16"
                  ></path>
                </svg>
              </label>
            </div>
          </div>
        </div>
        {/* second navabr */}
        {/* <div className="hidden md:block w-full navbar bg-sky-100">
          <div className="w-full grid place-content-center">
            <ul className="menu menu-horizontal text-black ">
              {navItems.map((navItem, i) => (
                <li key={i}>
                  <a className="font-semibold rounded-md">{navItem.name}</a>
                </li>
              ))}
            </ul>
          </div>
        </div> */}
        {/* Page content here  */}
        {children}
      </div>
      <div className="drawer-side ">
        <label htmlFor="my-drawer-3" className="drawer-overlay"></label>
        <ul className="menu p-4 overflow-y-auto w-[70%] bg-base-100 ">
          {navItems.map((navItem, i) => (
            <li key={i}>
              <a>{navItem.name}</a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default DefaultLayout;
